### ISSUE TITLE
用docker+自定义任务表后，脚本不运行

### ISSUE THREAD

**Issue by sorakirahk** [lxk0301/scripts#186]
因为只想做少数几个任务，所以用了自定义任务表
按照教程，使用的`docker-compose.yml`代码为
```
jd_scripts:
  image: akyakya/jd_scripts
  container_name: jd_scripts
  restart: always
  volumes:
    - ./logs:/scripts/logs
    - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
  tty: true
  environment:

    - JD_COOKIE=pt_key=***;pt_pin=***;

    - JOY_FEED_COUNT=*

    - MARKET_COIN_TO_BEANS=*

    - JD_DEBUG=true

    - CRONTAB_LIST_FILE=my_crontab_list.sh
  command:
    - /bin/sh
    - -c
    - |
      crontab /scripts/docker/my_crontab_list.sh
      crond
      node
```
自定义任务表代码
```
0 0/1 * * * git -C /scripts/ pull >> /scripts/logs/pull.log 2>&1
0 0-18/6 * * * node /scripts/jd_818.js >> /scripts/logs/jd_818.log 2>&1
0,10 0 * * * node /scripts/jd_xtg.js >> /scripts/logs/jd_xtg.log 2>&1
0 0,12,18 * * * node /scripts/jd_bean_sign.js >> /scripts/logs/jd_bean_sign.log 2>&1
0 0 * * * node /scripts/jd_blueCoin.js >> /scripts/logs/jd_blueCoin.log 2>&1
15 */1 * * * node /scripts/jd_joy_feedPets.js >> /scripts/logs/jd_joy_feedPets.log 2>&1
0 0-16/8 * * * node /scripts/jd_joy_reward.js >> /scripts/logs/jd_joy_reward.log 2>&1
10 0 * * * node /scripts/jd_shop.js >> /scripts/logs/jd_shop.log 2>&1
8 */3 * * * node /scripts/jd_speed.js >> /scripts/logs/jd_speed.log 2>&1
11 1-23/5 * * * node /scripts/jd_superMarket.js >> /scripts/logs/jd_superMarket.log 2>&1

```
按照教程建立了如下文件结构
```
jd_scripts
├── logs  
├── my_crontab_list.sh
└── docker-compose.yml
```
后面用ssh连入nas进入`jd_scripts`目录下，执行`docker-compose up -d`启动代码
启动后正常运行，到时间任务触发时，控制台里能看到脚本正常运行的log
```
crond[8]: USER root pid  42 cmd node /scripts/jd_joy.js >> /scripts/logs/jd_joy.log 2>&1
crond[8]: USER root pid  43 cmd node /scripts/jd_joy_feedPets.js >> /scripts/logs/jd_joy_feedPets.log 2>&1
```
但是实际进入到`jd_scripts`>>`logs`文件夹下，却没有看到脚本输出的log文件，文件夹为空

试着换为非自定义脚本后，脚本就能正常工作，并输出log文件

请问下用自定义脚本的时候是我什么地方弄错了吗，导致脚本运行不正常
